"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const router = express_1.default.Router();
const userController_1 = require("../controller/userController");
const userController_2 = require("../controller/userController");
const productController_1 = require("../controller/productController");
const productController_2 = require("../controller/productController");
const productController_3 = require("../controller/productController");
const productController_4 = require("../controller/productController");
const productController_5 = require("../controller/productController");
const cartControll_1 = require("../controller/cartControll");
const cartControll_2 = require("../controller/cartControll");
const cartControll_3 = require("../controller/cartControll");
const cartControll_4 = require("../controller/cartControll");
const cartControll_5 = require("../controller/cartControll");
const auth_1 = require("../middleware/auth");
const validation_1 = require("../middleware/validation");
router.post('/createUser', (0, validation_1.userValidation)(), userController_1.user);
router.post('/userLogin', userController_2.login);
router.post('/createProduct', auth_1.authentication, productController_1.product);
router.get('/getProductById/:productId', auth_1.authentication, productController_2.findOneProduct);
router.get('/getAllProduct', auth_1.authentication, productController_3.getAllProduct);
router.put('/updateProduct/:productId', auth_1.authentication, productController_4.updateProduct);
router.delete('/deleteProduct/:productId', auth_1.authentication, productController_5.deleteProduct);
router.post('/createCart', auth_1.authentication, cartControll_1.cart);
router.get('/getCartById/:cartId', auth_1.authentication, cartControll_2.getCart);
router.get('/getAllCart', auth_1.authentication, cartControll_3.getAllCart);
router.put('/updateCart/:cartId', auth_1.authentication, cartControll_4.updateCart);
router.delete('/deleteCart/:cartId', auth_1.authentication, cartControll_5.deleteCart);
exports.default = router;
